# Checks scripts.
name: scripts
on:
  pull_request:
  push:
permissions: read-all
jobs:
  run_scripts_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v6
    - name: Generate test data
      run: |
        ./generate-specimens-macos.sh
        ./generate-specimens-many-attributes-macos.sh
        ./generate-specimens-many-files-macos.sh
    - uses: actions/upload-artifact@v7
      with:
        name: specimens-macos
        path: specimens/*/*.dmg
